CREATE TABLE IF NOT EXISTS conferences(
    id varchar(100) NOT NULL,
    name varchar(255) NOT NULL,
    description text,
    program_id varchar(100) NOT NULL,
    people text,
    duration int NOT NULL DEFAULT 1,
   	original_start_date datetime NOT NULL,
  	original_end_date datetime NOT NULL,
 	revised_start_date datetime,
  	revised_end_date datetime,
	offered_start_date datetime,  
	offered_end_date datetime,
	is_ready tinyint(1) NOT NULL DEFAULT '0',
	actual_start_date datetime,
	actual_end_date datetime,
    cancelled_at datetime,
    closing_notes text,
 	created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	PRIMARY KEY (id),
    FOREIGN KEY (program_id) REFERENCES programs(id)
);